### ISSUE TITLE
Find a better alternative to the use of environment variables

### ISSUE THREAD

**Issue by tonybaloney** [tox-dev/tox-pipenv#35]
The plugin relies heavily on Pipenv's environment variables, since at the time of development (v9) the settings for Pipenv were in the global scope, they were loaded into the module at import.
See https://github.com/tox-dev/tox-pipenv/blob/master/tox_pipenv/plugin.py
If Pipenv changes to be an importable library instead of designed as a shell, this could change.

@kennethreitz if you have any thoughts on the right approach?

**Comment by kennethreitz** [comment]
I think that tox-pipenv is a bit hacky, but it looks like it'll "get the job done" for most people — kind of like tox itself :)

**Comment by kennethreitz** [comment]
We have no plans to library-ize, at this time. I think what you're doing is appropriate (and similar to what we're doing within our own test suite). That's the expected API.
