### ISSUE TITLE
Exact pin of tox==3.0.0 breaks pipenv with conflicts on 3.2.1

### ISSUE THREAD

**Issue by shentonfreude** [tox-dev/tox-pipenv#50]
In my project, if I do "pipenv install --dev tox" I get 3.2.1.
If I then do "pipenv install --dev tox-pipenv" I get a conflict because this plugin insists on exactly 3.0.0. 

Shouldn't tox-pipenv require something like "tox >=3.0.0" ?

**Comment by uSpike** [comment]
Looks like this was fixed in https://github.com/tox-dev/tox-pipenv/commit/1e278cfd758dfac236a53e5cee2b19653f221db1

**Comment by ferndot** [comment]
@tonybaloney please release this fix. It is a critical issue.

**Comment by toxeus** [comment]
@joshua-s currently tox-pipenv is broken for tox>=3.4.0. I have prepared a PR with a fix in #53. It would be good to include that into the release too. In the meantime, feel free to use my fork until upstream has made a proper release on pypi:
```sh
pip install git+https://github.com/toxeus/tox-pipenv.git
```

**Comment by sjrogers** [comment]
For anyone looking for a workaround: check out [this gist](https://gist.github.com/sjrogers/77cbfc3f241d8ad47c6fc4665bb0adef) for how I got it working without `tox-pipenv`.

To make a short story shorter, make `pipenv` a dependency for `testenv` in `tox.ini` and put `pipenv install` before your test runner in `commands`.

**Comment by tonybaloney** [comment]
Will get this released. Sorry for the delays

**Comment by tonybaloney** [comment]
Fixed in 1.7.0 (released)
