### ISSUE TITLE
Project development

### ISSUE THREAD

**Issue by uhurusurfa** [tox-dev/tox-pipenv#65]
@asottile @dcrosta @nicoddemus @gaborbernat @obestwalter @rpkilby @The-Compiler 
If you need someone to pick up the project and continue the great work you guys have done let me know.
There is a key fix that needs doing for tox >= 3.8 and has been a PR for many months now and it would make this project usable again.
So - happy to help if you neeed it otherwise would appreciate anyone jumping in and doing some of the PR reviews and merge.

**Comment by gaborbernat** [comment]
@uhurusurfa we'd be happy to accept your help offer; do you already have a PR you're referring to? I don't use pipenv, so I'm not too much use myself 🤔

**Comment by gaborbernat** [comment]
@tonybaloney been the active maintainer lately 😊

**Comment by uhurusurfa** [comment]
@gaborbernat - thanks for the reply. there is just the one PR https://github.com/tox-dev/tox-pipenv/pull/62
It does need a little work like removing print statements and fixing the lne that somone else identified.
If you can make me a contributor I will review and get it to a mergeable state.

**Comment by gaborbernat** [comment]
Without the consent of one of the active maintainers, I cannot put you on the maintainer list right away, but feel free to put in another PR that fixes fully the issue, and can take a look at it. Then we might close #62 and merge yours.

**Comment by uhurusurfa** [comment]
@gaborbernat Here you go:
https://github.com/tox-dev/tox-pipenv/pull/66
